Remndr/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('',include("rem.urls", namespace="rem")),
]

rem/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'rem'

urlpatterns = [
    path('new/',views.CreateRem.as_view(),name = "createrem"),
    path('remlist/',views.ListRem.as_view(),name = "remlist"),
    url(r'^rem/(?P<pk>\d+)/edit/$',views.UpdateRem.as_view(),name = "updaterem"),
]

rem/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class rem(models.Model):
    rem_name = models .CharField(max_length=256,unique=True)
    rem_on = models.DateTimeField()

    def __str__(self):
        return self.rem_name

Remndr/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'home.html'

rem/views.py
from django.shortcuts import render
from .models import rem
from django.urls import reverse_lazy
from django.views.generic import (CreateView, ListView, UpdateView, DeleteView)
# Create your views here.
class CreateRem(CreateView):
     fields = ("rem_name","rem_on")
     model = rem

     def get_success_url(self):
         return reverse_lazy("rem:remlist")

class ListRem(ListView):
     model = rem

class UpdateRem(UpdateView):
     fields = ("rem_name","rem_on")
     model= rem
     template_name = "rem/update_form.html"

     def get_success_url(self):
         return reverse_lazy("rem:remlist")

rem/templates/rem/rem_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <h2>New Reminder</h2>
  <form method="POST" action="{% url 'rem:createrem' %}"class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <p>Date enter format : month/day/year</p>
    {% buttons %}
      <button type="submit" class="btn btn-primary">Done</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

rem/templates/rem/rem_list.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">

    <h4>Added Reminders are shown below.</h4><br>

    {% for rem in object_list %}
    <ul>
      <li><a href="{% url 'rem:updaterem' pk=rem.pk %}" class="btn btn-primary a-btn-slide-text">
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        <span><strong>Edit</strong></span>
    </a>
          <h4>{{rem.rem_name}}</h4>
          <p>{{rem.rem_on}}</p>
      </li>
    </ul>

    {% endfor %}

  </div>
</div>
{% endblock %}

rem/templates/rem/update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <h2>Update Reminder</h2>
  <form method="POST" action="" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <p>Date enter format : month/day/year</p>
    {% buttons %}
      <button type="submit" class="btn btn-primary">Done</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">REMINDER</a>
        </div>
        <div class="navbar-nav ml-auto">

            <a class="nav-item nav-link" href="{% url 'rem:remlist' %}" class="btn btn-simple">Reminder List</a>
            <a class="nav-item nav-link" href="{% url 'rem:createrem' %}" class="btn btn-simple">Add Reminder</a>


        </div>
      </div>
    </nav>
    <div class="container mycontent">
        {% block content %}

        {% endblock %}
      </div>

  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container mycontent">
  <div class="jumbotron">

<h1>REMINDER</h1>
<h5>| Lets You Know |</h5>
<div class="container">
  <img src="{% static "Remndr/images/remn.jpg" %}" alt="">
</div><br>
<p>REMINDER! handle your forgetfullness.</p>
<p>This App enables you to keep reminders for events like birthdays and other things in your
  everday busy life between family, friends and work.</p>
  <h6>So Be Little Forgetful !.</h6>

</div>
</div>


{% endblock %}